import type { NewsState } from "../../../redux-toolkit/newsSlice";

export const normalizeNewsResponse = (
  data: any,
  languageCode: string | null
): NewsState => ({
  status: data.status ?? "draft",
  published_at: data.published_at ?? null,
  scheduled_at: data.scheduled_at ?? null,
  read_time: data.read_time ?? 0,
  restriction_type: data.restriction_type ?? "free",
  entitlements: data.entitlements ?? [],
  must_be_logged_in: data.must_be_logged_in ?? false,
  must_be_verified: data.must_be_verified ?? false,
  must_be_over_18: data.must_be_over_18 ?? false,
  is_featured: data.is_featured ?? false,
  publish_platforms: data.publish_platforms ?? [],
  geo_block_mode: data.geo_block_mode ?? null,
  geo_block_countries: data.geo_block_countries ?? [],
  // tag_ids: data.tags?.map((tag: any) => tag.id) ?? [],
  tag_ids: data.tags ?? [],
  // category_ids: data.categories?.map((cat: any) => cat.id) ?? [],
  category_ids: data.categories ?? [],
  // player_ids: data.players?.map((p: any) => p.id) ?? [],
  player_ids: data.players ?? [],
  tournament_ids: data.tournaments ?? [],
  metadata: {
    seo_title: data.metadata?.seo_title ?? "",
    seo_tag: data.metadata?.seo_tag ?? "",
    seo_description: data.metadata?.seo_description ?? "",
  },
  translation: {
    language_code: languageCode || "en",
    title: data.title ?? null,
    description: data.description ?? null,
    sponsor_name: data.sponsor_name ?? null,
    sponsor_logo_url: data.sponsor_logo_url ?? null,
    sponsor_url: data.sponsor_url ?? null,
    hero_title: data.hero_title ?? null,
    hero_description: data.hero_description ?? null,
    hero_image_url: data.hero_image_url ?? null,
    img_width: data.img_width ?? 0,
    img_height: data.img_height ?? 0,
    hero_video_source: data.hero_video_source ?? null,
    hero_video_url: data.hero_video_url ?? null,
    hero_media_type: data.hero_media_type ?? null,
    hero_media_thumbnail: data.hero_media_thumbnail ?? null,
    thumbnail_width: data.thumbnail_width ?? 0,
    thumbnail_height: data.thumbnail_height ?? 0,
    author_name: data.author_name ?? null,
    author_title: data.author_title ?? null,
    author_image_url: data.author_image_url ?? null,
    author_social_urls: data.author_social_urls ?? {},
  },
  blocks: data.blocks ?? [],
});
