import type { PageState } from "../../redux-toolkit/pageSlice";

export const normalizePageResponse = (
  data: any,
  languageCode?: string | null,
): PageState => ({
  status: data?.status ?? "draft",
  published_at: data?.published_at ?? null,
  scheduled_at: data?.scheduled_at ?? null,
  read_time: data?.read_time ?? 0,
  restriction_type: data?.restriction_type ?? "free",
  entitlements: data?.entitlements ?? [],
  must_be_logged_in: data?.must_be_logged_in ?? false,
  must_be_verified: data?.must_be_verified ?? false,
  must_be_over_18: data?.must_be_over_18 ?? false,
  publish_platforms: data?.publish_platforms ?? [],
  geo_block_mode: data?.geo_block_mode ?? null,
  geo_block_countries: data?.geo_block_countries ?? [],
  tag_ids: data?.tags?.map((tag: any) => tag.id) ?? [],
  category_ids: data?.categories?.map((cat: any) => cat.id) ?? [],
  player_ids: data?.players?.map((p: any) => p.id) ?? [],
  metadata: {
    seo_title: data?.metadata?.seo_title ?? "",
    seo_tag: data?.metadata?.seo_tag ?? "",
    seo_description: data?.metadata?.seo_description ?? "",
  },
  hero_media: data?.hero_media ?? [],
  hero_type: data?.hero_type ?? "",
  platform_type: data?.platform_type ?? "",
  parent_id: data?.parent_id ?? null,
  translation: {
    language_code: languageCode || "en",
    title: data?.title ?? null,
    description: data?.description ?? null,
    sponsor_name: data?.sponsor_name ?? null,
    sponsor_logo_url: data?.sponsor_logo_url ?? null,
    sponsor_url: data?.sponsor_url ?? null,
    author_name: data?.author_name ?? null,
    author_title: data?.author_title ?? null,
    author_image_url: data?.author_image_url ?? null,
    author_social_urls: data?.author_social_urls ?? {},
  },
  blocks: data?.blocks ?? [],
});
