export const normalizeVideoResponse = (data: any = {}, languageCode: any) => {
  return {
    status: data.status || "draft",
    source_type: data.source_type || "",
    video_url: data.video_url || "",
    video_id: data.video_id || "",
    video_thumbnail: data.video_thumbnail || "",
    duration: data.duration || null,
    published_at: data.published_at || null,
    scheduled_at: data.scheduled_at || null,
    read_time: data.read_time || 0,
    restriction_type: data.restriction_type || "free",
    type: data.type || "",
    // entitlements: data.entitlements || [],
    must_be_logged_in: !!data.must_be_logged_in,
    must_be_verified: !!data.must_be_verified,
    must_be_over_18: !!data.must_be_over_18,
    // publish_platforms: data.publish_platforms || [],
    geo_block_mode: data.geo_block_mode || null,
    geo_block_countries: data.geo_block_countries || [],
    tag_ids: data.tags?.map((tag: any) => tag.id) || [],
    category_ids: data.categories?.map((cat: any) => cat.id) || [],
    player_ids: data.players?.map((player: any) => player.id) || [],
    tournament_ids:
      data.tournaments?.map((tournament: any) => tournament.id) || [],
    metadata: {
      seo_title: data.metadata?.seo_title || "",
      seo_tag: data.metadata?.seo_tag || "",
      seo_description: data.metadata?.seo_description || "",
    },
    translation: {
      language_code: languageCode || "en",
      title: data.title || null,
      description: data.description || null,
      sponsor_name: data.sponsor_name || null,
      sponsor_logo_url: data.sponsor_logo_url || null,
      sponsor_url: data.sponsor_url || null,
      hero_title: data.hero_title || null,
      hero_description: data.hero_description || null,
      hero_image_url: data.hero_image_url || null,
      hero_video_source: data.hero_video_source || null,
      hero_video_url: data.hero_video_url || null,
      hero_media_type: data.hero_media_type || null,
      author_name: data.author_name || null,
      author_title: data.author_title || null,
      author_image_url: data.author_image_url || null,
      image: data?.image || null,
      video_url: data?.video_url || null,
      author_social_urls: data.author_social_urls || {},
    },
    blocks: data.blocks || [],
  };
};
